exports.actors = [
  'Gary Oldham',
  'Casey Affleck',
  'Leonardo DiCaprio',
  'Eddie Redmayne',
  'Matthew McConaughey',
  'Daniel Day Lewis',
  'Colin Firth',
  'Jeff Bridges',
  'Sean Penn',
  'Forest Whitaker',
  'Philip Seymour Hoffman',
  'Jamie Fox',
  'Adrien Brody',
  'Denzel Washington',
  'Russell Crowe',
  'Frances McDormand',
  'Emma Stone',
  'Brie Larson',
  'Julianne Moore',
  'Cate Blanchett',
  'Jennifer Lawrence',
  'Meryl Streep',
  'Natalie Portman',
  'Sandra Bullock',
  'Kate Winsley',
  'Marion Cotillard',
  'Helen Mirren',
  'Reese Witherspoon',
  'Hilary Swank',
  'Charlize Theron',
  'Nicole Kidman',
  'Halle Berry',
  'Julia Roberts'
];
